name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./apps/frontend
        push: true
        tags: navaneeth277/frontend:${{ env.IMAGE_TAG }}

    - name: Build & Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./apps/backend
        push: true
        tags: navaneeth277/backend:${{ env.IMAGE_TAG }}
